-- RETURNS -
-- 0 -> WHEN REQUEST IS SUCCESSFULLY MADE
-- 1 -> NOT A SUBSCRIBER
-- 2 -> ALREADY REQUESTED THE BOOK (REQUEST IS PENDING FOR THIS BOOK)
-- 3 -> ALREADY BORROWED THE BOOK


CREATE OR REPLACE FUNCTION REQUEST_TO_BORROW(ARG_CUSTOMER_ID VARCHAR2, ARG_ISBN VARCHAR2, ARG_CURRENT_TIME DATE)
RETURN NUMBER IS
    CNT_SUBSCRIBERS NUMBER;
    CNT_BOOK_WITH_SAME_ISBN_IN_REQUESTS NUMBER;
    CNT_BOOK_WITH_SAME_ISBN_IN_BORROWS NUMBER;
    BEGIN
        REMOVE_EXPIRED_SUBSCRIBERS(ARG_CURRENT_TIME);
        SELECT COUNT(*) INTO CNT_SUBSCRIBERS FROM SUBSCRIBERS WHERE CUSTOMER_ID = ARG_CUSTOMER_ID;
        IF CNT_SUBSCRIBERS = 0 THEN
            RETURN 1;
        END IF;

        SELECT COUNT(*) INTO CNT_BOOK_WITH_SAME_ISBN_IN_REQUESTS
        FROM REQUESTS
        WHERE CUSTOMER_ID =ARG_CUSTOMER_ID
        AND ISBN = ARG_CUSTOMER_ID;

        IF CNT_BOOK_WITH_SAME_ISBN_IN_REQUESTS <> 0 THEN
            RETURN 2;
        END IF;

        SELECT COUNT(*) INTO CNT_BOOK_WITH_SAME_ISBN_IN_BORROWS
        FROM BORROWABLE_ITEMS B_ITEM
        WHERE ISBN = ARG_ISBN
        AND BORROWABLE_ITEM_ID IN (
            SELECT BORROWABLE_ITEM_ID FROM BORROWS WHERE CUSTOMER_ID = ARG_CUSTOMER_ID
            );

        IF CNT_BOOK_WITH_SAME_ISBN_IN_BORROWS <> 0 THEN
            RETURN 3;
        END IF;

        INSERT INTO REQUESTS(CUSTOMER_ID, ISBN) VALUES (ARG_CUSTOMER_ID, ARG_ISBN);
        RETURN 0;
    END;
/
