-- RETURNS -
-- 0 IF NOT SUCCESSFULL

CREATE OR REPLACE FUNCTION ADD_BOOK_TO_BORROWABLE(ARG_ISBN IN VARCHAR2)
RETURN NUMBER IS

    V_QUANTITY NUMBER;
    BEGIN
        SELECT QUANTITY INTO V_QUANTITY FROM BOOKS WHERE ISBN = ARG_ISBN;
        IF V_QUANTITY = 0 THEN
            RETURN V_QUANTITY;
        END IF;

        INSERT INTO BORROWABLE_ITEMS(ISBN) VALUES (ARG_ISBN);

        SELECT QUANTITY INTO V_QUANTITY FROM BOOKS WHERE ISBN = ARG_ISBN;
        RETURN V_QUANTITY;

        EXCEPTION
         WHEN NO_DATA_FOUND THEN
            RETURN 0;
    END;
/
