CREATE OR REPLACE PROCEDURE UPDATE_PERSONAL_INFO (
			ARG_NAME IN VARCHAR2,
			ARG_EMAIL IN VARCHAR2,
			ARG_ADDRESS IN VARCHAR2,
			ARG_CID IN VARCHAR2
			) IS
	BEGIN
			UPDATE CUSTOMERS
			SET
				NAME = INITCAP(ARG_NAME),
				EMAIL = ARG_EMAIL,
				ADDRESS = INITCAP(ARG_ADDRESS)
			WHERE CUSTOMER_ID=ARG_CID;
	END;
/
