CREATE OR REPLACE PROCEDURE REMOVE_EXPIRED_SUBSCRIBERS (ARG_CURRENT_DATE IN DATE) IS

	BEGIN
		DELETE FROM SUBSCRIBERS WHERE CUSTOMER_ID IN (
				SELECT S.CUSTOMER_ID
				FROM SUBSCRIBERS S
				INNER JOIN PLANS P USING(PLAN_ID)
				WHERE S.MEMBERSHIP_BOUGHT_ON+P.PERIOD < ARG_CURRENT_DATE
				);
	END;
/
