CREATE OR REPLACE PROCEDURE UPDATE_OFFER_BOOK_INFO (ARG_ISBN IN VARCHAR2, ARG_OFFER_ID IN NUMBER) IS
		CNT_OFFER_BOOK NUMBER;
		CNT_OFFER NUMBER;
	BEGIN
		SELECT COUNT(*) INTO CNT_OFFER_BOOK FROM OFFER_BOOK WHERE ISBN = ARG_ISBN;
		IF ARG_OFFER_ID IS NULL THEN
			DELETE FROM OFFER_BOOK WHERE ISBN = ARG_ISBN;
			RETURN;
		END IF;

		SELECT COUNT(*) INTO CNT_OFFER FROM OFFERS WHERE OFFER_ID = ARG_OFFER_ID AND START_DATE >= SYSDATE-PERIOD;
		IF CNT_OFFER <> 0 THEN
			IF CNT_OFFER_BOOK = 0 THEN
				INSERT INTO OFFER_BOOK (ISBN, OFFER_ID) VALUES(ARG_ISBN, ARG_OFFER_ID);
			ELSE
				UPDATE OFFER_BOOK SET OFFER_ID = ARG_OFFER_ID WHERE ISBN = ARG_ISBN;
			END IF;

		END IF;



	END;
/
