CREATE OR REPLACE PROCEDURE INSERT_AUTHOR_INFO (
		ARG_NAME IN VARCHAR2,
		ARG_DOB IN DATE,
		ARG_DOD IN DATE,
		ARG_ABOUT IN VARCHAR2,
		RET_AUTHOR_ID OUT INTEGER
) IS
		A_ID INTEGER;
	BEGIN
		A_ID := AUTHOR_ID_AUTOINCREMENT_SEQ.NEXTVAL;
		INSERT INTO AUTHORS (
			AUTHOR_ID,
			NAME,
			DOB,
			DOD,
			ABOUT
		) VALUES (
			A_ID,
			ARG_NAME,
			ARG_DOB,
			ARG_DOD,
			ARG_ABOUT
		);
		RET_AUTHOR_ID := A_ID;
	END;
/
