CREATE OR REPLACE PROCEDURE INSERT_BOOK_INFO (
		ARG_ISBN IN VARCHAR2,
		ARG_BOOKNAME IN VARCHAR2,
		ARG_AUTHOR_ID IN NUMBER,
		ARG_EDITION IN VARCHAR2,
		ARG_RELEASE_DATE IN DATE,
		ARG_PRICE IN NUMBER,
		ARG_PAGE_COUNT IN NUMBER,
		ARG_QUANTITY IN NUMBER,
		ARG_PUBLISHER_ID IN NUMBER
	) IS
		CNT_BOOK_IN_WRITES NUMBER;
	BEGIN
		INSERT INTO BOOKS(
				ISBN,
				NAME,
				EDITION,
				RELEASE_DATE,
				PRICE,
				PAGE_COUNT,
				QUANTITY,
				PUBLISHER_ID
			) VALUES (
				ARG_ISBN,
				INITCAP(ARG_BOOKNAME),
				ARG_EDITION,
				ARG_RELEASE_DATE,
				ARG_PRICE,
				ARG_PAGE_COUNT,
				ARG_QUANTITY,
				ARG_PUBLISHER_ID
			);
		SELECT COUNT(*) INTO CNT_BOOK_IN_WRITES FROM WRITES WHERE AUTHOR_ID=ARG_AUTHOR_ID AND ISBN=ARG_ISBN;
		IF CNT_BOOK_IN_WRITES = 0 THEN
			INSERT INTO WRITES(
					AUTHOR_ID,
					ISBN
				) VALUES (
					ARG_AUTHOR_ID,
					ARG_ISBN
				);
		END IF;
		COMMIT;
	END;
/
