CREATE SEQUENCE AUTHOR_ID_AUTOINCREMENT_SEQ
START WITH 1000
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER AUTHOR_ID_AUTOINCREMENT
BEFORE INSERT
ON AUTHORS
FOR EACH ROW
DECLARE

BEGIN
	IF :NEW.AUTHOR_ID IS NULL THEN
		:NEW.AUTHOR_ID := AUTHOR_ID_AUTOINCREMENT_SEQ.NEXTVAL;
	END IF;


END;
