CREATE OR REPLACE TRIGGER DECREASE_BOOK_QUANTITY_ON_BORROWABLE_INSERT
    AFTER INSERT
    ON BORROWABLE_ITEMS
    FOR EACH ROW
    DECLARE
        V_QUANTITY NUMBER;
    BEGIN
        SELECT QUANTITY INTO V_QUANTITY FROM BOOKS WHERE ISBN = :NEW.ISBN;
        IF V_QUANTITY > 0 THEN
            UPDATE BOOKS SET QUANTITY = QUANTITY - 1 WHERE ISBN = :NEW.ISBN;
        END IF;

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                DBMS_OUTPUT.PUT_LINE('BOOK NOT AVAILABLE');
    END;
/
