CREATE OR REPLACE TRIGGER CLEAN_BORROWS_AND_REQUESTS_FOR_SUBSCRIBERS
AFTER DELETE
ON SUBSCRIBERS
FOR EACH ROW
	DECLARE
	ARG_ISSUE_DATE DATE;
	BEGIN
		DELETE FROM REQUESTS WHERE CUSTOMER_ID = :OLD.CUSTOMER_ID;
		SELECT (:OLD.MEMBERSHIP_BOUGHT_ON+P.PERIOD) INTO ARG_ISSUE_DATE FROM PLANS P WHERE PLAN_ID = :OLD.PLAN_ID;
		FOR R IN (
				SELECT * FROM BORROWS WHERE CUSTOMER_ID = :OLD.CUSTOMER_ID AND END_DATE IS NULL
							)
			LOOP
				INSERT INTO EXPIRED(CUSTOMER_ID, BORROWABLE_ITEM_ID, ISSUE_DATE) VALUES(R.CUSTOMER_ID, R.BORROWABLE_ITEM_ID, ARG_ISSUE_DATE);
			END LOOP;
		DELETE FROM BORROWS WHERE CUSTOMER_ID=:OLD.CUSTOMER_ID;
	END;
/
