CREATE OR REPLACE TRIGGER UPDATE_BOOK_QUANTITY_ON_CANCEL_ORDER
AFTER DELETE
ON ORDER_BOOK
FOR EACH ROW
 DECLARE
 BEGIN
	UPDATE BOOKS B SET B.QUANTITY = B.QUANTITY + :OLD.QUANTITY WHERE B.ISBN = :OLD.ISBN;
 END;
/
